CREATE TABLE todos (
    id VARCHAR(255),
    title VARCHAR(500) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT todos_pkey PRIMARY KEY (id)
);

CREATE TABLE todos_audit (
    id SERIAL PRIMARY KEY,
    todo_id VARCHAR(255) NOT NULL,
    action VARCHAR(10) NOT NULL,
    description VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
